name: Divvy Dashboard Listing Request
description: Provide details about your project.
title: "[Listing Request]: <project name>"
labels: ["listing"]
assignees: 
 - FEGjoshua
body:
 - type: markdown
   attributes:
     value: "A full listing on the dashboard requires a deposit of 1% of the total supply in the Divvy Fund 0xb80267ea7fa368374ee4d4bf10044778232adefe"
 - type: input
   id: contract_address
   attributes:
     label: Contract Address
   validations:
     required: true
 - type: input
   id: project_name
   attributes:
     label: Project Name
   validations:
     required: true
 - type: input
   id: token_symbol
   attributes:
     label: Token Symbol
   validations:
     required: true
 - type: input
   id: primary_color
   attributes:
     label: Custom Color
     placeholder: HTML Hex Color Code (#BADA55)
 - type: checkboxes
   id: divvy_locker
   attributes:
     label: Interested in Divvy Locker and Lava Flow?
     description: Divvy Locker is a service to lock team tokens. Lava Flow is a faucet for your project. For 1 BNB buy/burn of Volcano (LAVA) you get both.
     options:
      - label: "Yes"
